#!bash/bash
alias update="apt update -y && apt upgrade -y"
alias addi386="dpkg --add-architecture i386 && apt update -y && apt install lib32gcc-s1 lib32stdc++6 libc6-i386 libcurl4-gnutls-dev:i386 libsdl2-2.0-0:i386"
alias installsteamcmd="add-apt-repository multiverse && cd && apt install steamcmd && cd /usr/games && chmod +x * && ./steamcmd +force_install_dir /home/xash/ +login anonymous +app_update 90 validate +exit"
alias tools="apt install unzip -y && apt install wget -y && apt install apache2 && apt update -y"

#install-libs-and-softweres
echo "updating..."
sleep 3
update

#add-i386
clear 
echo "(2-6) add-i386libs..." 
sleep 3 
addi386

#install-steamcmd
clear
echo "(3-6) installing steamcmd..."
sleep 3
installsteamcmd

#tools
clear
echo "(4-6) installing-tools..."
sleep 3
tools

#choice-game-lib-u-wont
clear
echo "(5-6) select-game..."
sleep 3
cd
wget https://raw.githubusercontent.com/happyhere-TN/HLDS_CHOICE--private-/blob/main/choiceengine.sh && sh choiceengine.sh
